[build]
  base    = "ui"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxQ7HIztpGnAWRmhbTRvi-jFBOIChfZshH7fkTaBg81LDaDLfgmfXTOw5kqRJMWqMQ/exec"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
